/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface": "#15130e",
        "on-primary": "#16362a",
        "on-tertiary-fixed": "#131f06",
        "on-tertiary-container": "#92a27d",
        "tertiary-fixed": "#d7e9bf",
        "surface-container-highest": "#37342e",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#3d4b2d",
        "on-background": "#e8e1d9",
        "on-secondary-fixed-variant": "#5a4302",
        "tertiary": "#bccca5",
        "tertiary-container": "#2b381c",
        "outline-variant": "#414844",
        "surface-tint": "#abcebd",
        "primary-fixed": "#c7ebd9",
        "inverse-surface": "#e8e1d9",
        "secondary-fixed-dim": "#e4c278",
        "inverse-on-surface": "#33302a",
        "on-surface-variant": "#c1c8c3",
        "on-error-container": "#ffdad6",
        "primary-container": "#1a3a2e",
        "on-primary-fixed": "#002116",
        "on-primary-container": "#82a494",
        "on-surface": "#e8e1d9",
        "surface-container-lowest": "#100e09",
        "secondary": "#e4c278",
        "surface-container-high": "#2c2a24",
        "on-secondary": "#3f2e00",
        "secondary-fixed": "#ffdf9b",
        "on-secondary-fixed": "#251a00",
        "background": "#15130e",
        "secondary-container": "#5d4604",
        "tertiary-fixed-dim": "#bccca5",
        "on-tertiary": "#273418",
        "surface-variant": "#37342e",
        "surface-dim": "#15130e",
        "outline": "#8b928e",
        "error": "#ffb4ab",
        "surface-container": "#221f1a",
        "surface-container-low": "#1e1b16",
        "inverse-primary": "#456557",
        "primary": "#abcebd",
        "on-error": "#690005",
        "primary-fixed-dim": "#abcebd",
        "on-primary-fixed-variant": "#2d4d40",
        "on-secondary-container": "#d5b46b",
        "surface-bright": "#3c3933",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "128px",
        "margin-page": "64px",
        unit: "8px",
        gutter: "32px",
      },
      fontFamily: {
        "display-ar":  ["Aref Ruqaa", "serif"],
        "display-lat": ["Cormorant Garamond", "serif"],
        "headline-md": ["Cormorant Garamond", "serif"],
        "label-sm":    ["Inter", "sans-serif"],
        "body-md":     ["Inter", "sans-serif"],
        "body-lg":     ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-ar":  ["48px",  { lineHeight: "1.2",  fontWeight: "400" }],
        "display-lat": ["42px",  { lineHeight: "1.1",  fontWeight: "400" }],
        "headline-md": ["28px",  { lineHeight: "1.3",  fontWeight: "500" }],
        "label-sm":    ["12px",  { letterSpacing: "0.1em", fontWeight: "400" }],
        "body-md":     ["16px",  { lineHeight: "1.6",  fontWeight: "300" }],
        "body-lg":     ["18px",  { lineHeight: "1.6",  letterSpacing: "0.02em", fontWeight: "300" }],
      },
    },
  },
  plugins: [],
}
